// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANxnW1PZ_C_fb1_p8B0y6q4QtEL8fNI1c',
    appId: '1:764791811000:web:236db65c382d007c6d3d4d',
    messagingSenderId: '764791811000',
    projectId: 'chess-game-30',
    authDomain: 'chess-game-30.firebaseapp.com',
    storageBucket: 'chess-game-30.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBc3RTUIXJKuaXTj9RCWqgyHqOf_hYI3l0',
    appId: '1:764791811000:android:ffcb39e26fa069746d3d4d',
    messagingSenderId: '764791811000',
    projectId: 'chess-game-30',
    storageBucket: 'chess-game-30.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8oHDFEovxaJ4lejuRtKFOWVBWyYsVnLs',
    appId: '1:764791811000:ios:8376aac52bebfd1f6d3d4d',
    messagingSenderId: '764791811000',
    projectId: 'chess-game-30',
    storageBucket: 'chess-game-30.firebasestorage.app',
    iosBundleId: 'com.example.chess',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8oHDFEovxaJ4lejuRtKFOWVBWyYsVnLs',
    appId: '1:764791811000:ios:8376aac52bebfd1f6d3d4d',
    messagingSenderId: '764791811000',
    projectId: 'chess-game-30',
    storageBucket: 'chess-game-30.firebasestorage.app',
    iosBundleId: 'com.example.chess',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANxnW1PZ_C_fb1_p8B0y6q4QtEL8fNI1c',
    appId: '1:764791811000:web:7570241e99c5be716d3d4d',
    messagingSenderId: '764791811000',
    projectId: 'chess-game-30',
    authDomain: 'chess-game-30.firebaseapp.com',
    storageBucket: 'chess-game-30.firebasestorage.app',
  );

}