# Generated by Django 4.2 on 2026-02-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0005_alter_user_last_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='draws',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
